### ISSUE TITLE
libssh2 error

### ISSUE THREAD

**Issue by rheydt** [git-time-metric/gtm#1]
Using Windows 7 OS. 
Downloaded the Windows installer (newest beta release v1.0-beta.3). 
Ran installer, installed the program in default location ( C:\Program Files (x86)\gtm ).
Navigated to the .exe program file in my new gtm folder, double-clicked to run.
Command Prompt window opened and error message popped up:

![image](https://cloud.githubusercontent.com/assets/3317631/16525250/75bdfd2e-3f79-11e6-805a-6faa6f5e3f74.png)

**Comment by mschenk42** [comment]
Darn, I was hoping that was not going to be an issue.  GTM does not technically need libssh2 but we have been unable to get it to build without it on the Windows platform.  You can see this in the [AppVeyor build](https://ci.appveyor.com/project/mschenk42/gtm).  So the solution should be for us to fix the build process. 

Can you tell me a little bit about how Git is installed on your system and how you use it?  Do you use Git via the command line or a Git Windows client?  Are you using [Git Bash](https://git-for-windows.github.io)?

**Comment by mschenk42** [comment]
I was able to reproduce this issue with a fresh install of Windows.  Stay tuned for the fix.

**Comment by mschenk42** [comment]
This issue should now be resolved.  The build process has been updated to eliminate the need for libssh2.  Please download the latest release for this fix.  Let us know if you have any further issues.
