### ISSUE TITLE
Problems with git hooks

### ISSUE THREAD

**Issue by con-ssc** [git-time-metric/gtm#11]
![image](https://cloud.githubusercontent.com/assets/8189808/17326212/1b9a4938-58b0-11e6-90ee-ce835d8daba6.png)
When trying to init I get an error pointing at a post commit hook

> gtm init
open .git\hooks\post-commit: The system cannot find the path specified.

**Comment by mschenk42** [comment]
From the root of your project can you check if the hooks directory exists?  I assume you are running Windows and you need to run `dir .git\hooks`.  Let me know what it returns.

When you do a `git init` the hooks directory is automatically created.  Is it possible it was deleted?  I believe you "should" be able to safely `git init` again if the directory doesn't exists.

**Comment by con-ssc** [comment]
It exists and it has some custom hooks. It is an existing repo.

**Comment by mschenk42** [comment]
`gtm init` is trying to add or modify the post-commit hook.  It adds `gtm commit --yes` to the post-commit hook script.

I think the issue is that I assume the post-commit hook exists, which it usually does with the standard `git init`.  

Can you check to see if the `post-commit` script exists within the `hooks`?

**Comment by con-ssc** [comment]
You are absolutely right. All sample hooks were there except post-commit, weird.

**Comment by con-ssc** [comment]
reinitializing with git init did not do the trick. Can you create the hook if it does not exist?

**Comment by mschenk42** [comment]
You can try creating the `post-commit` file in the hooks directory and then run `gtm init`.  

I plan to fix the issue and do a release this weekend if I confirm the issue is caused by it not already existing.

**Comment by mschenk42** [comment]
So I tried to reproduce this issue with a unit test.  No luck, looks like I handle the case where the post-commit doesn't exist.

You could try to create the post-commit but I don't think that will work for you.  

Would it be possible to share your repo with me so I can clone it and test locally?

If not, here's a few things that would be helpful for troubleshooting.

- Where are running `git init` in?  Command Prompt, Powershell, Git Bash, etc.
- What version of gtm, `gtm -version`
- What's the directory tree structure from your project root, in particular the `.git` subdirectory within the project root
- What's the  `git version`

**Comment by mschenk42** [comment]
Another thing we can try is to create a new git repo and see if you have the same issues.
