### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by ajsb85** [git-time-metric/gtm#12]
Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
```
property 'document' of undefined
    at C:\Users\username\.vscode\extensions\s3ramsay.vscode-gtm-0.0.3\out\src\extension.js:48:88
```

VS Code v1.4

**Comment by gradymke** [comment]
I think this is an issue with the VS.CODE plugin. Would you mind logging the issue there? The repository can be found here:

https://github.com/nexus-uw/vscode-gtm

**Comment by ajsb85** [comment]
Yes, you alright, @gradymke thanks
