### ISSUE TITLE
Question about tracking time

### ISSUE THREAD

**Issue by nicknikolov** [git-time-metric/gtm#13]
Hi there - this is a very cool piece of software and I would like to start using it but I have some problems understanding exactly how it works. I use Vim and installed the plugin. I opened a file and read it for two minutes, then exited vim. However, when I call gtm status repeatedly after that the time it shows me keeps growing even though I'm not reading that file anymore. Is it expected behaviour?

Thanks a lot!

UPDATE: seems like time stops being added after a couple of minutes...

**Comment by mschenk42** [comment]
How much extra time do you see added after exiting? The time tracking algorithm will add up to 2 minutes of idle time by design.  Technically you may see up to 3 additional minutes depending on when you run `gtm status`.  

Idle time takes into account "think time", when you're not actively typing or moving the mouse,  but you're likely still "working".

You can learn more about the algorithm here, https://github.com/git-time-metric/gtm/wiki/Time-Tracking-Algorithm.

Let me know if you are seeing something different than what I've stated here.

Thanks.

**Comment by nicknikolov** [comment]
Thanks for the reply. 

I think it was 2-3 minutes, yes. I think the concept of idle time makes a lot of sense (and I probably spend more than 3 minutes thinking in front of my editor quite often). My confusion came from the fact that I closed my editor. Doesn't that mean every time I stop working on a project I will get an extra few minutes? I will use it a bit more and see if this was maybe some glitch.

**Comment by mschenk42** [comment]
Correct, you will always have an extra couple of minutes (less 3 minutes) added at the end of your work session.  The reason for this is GTM doesn't know when you are officially done working.

**Comment by mschenk42** [comment]
BTW, one of things on the roadmap is to allow idle timeout to be configured.

**Comment by nicknikolov** [comment]
Ok I see. Sorry to keep banging on about this. Would it be technically easy to stop the clock (maybe using some config flag) when I close my editor? This would provide for a nice mechanism when having short breaks without adding up extra minutes. I already found about `gtm clean` which seems like an alternative otherwise. I don't want to open another issue but I also wanted to ask if you have a way to see a global list of the projects you are working on.

Thanks a lot. Feel free to close this issue when replying.

**Comment by mschenk42** [comment]
NP on the questions.  I could make it configurable to turn on/off adding idle time to the last event.  Here's part of the algorithm used to determine time spent working.  See that last part of the method for where it adds idle time for the last event.

https://github.com/git-time-metric/gtm/blob/master/event/manager.go#L29,L106

**Comment by nicknikolov** [comment]
I see. What I was thinking in the beginning is maybe using Vim autocmd on close? http://vimdoc.sourceforge.net/htmldoc/autocmd.html#VimLeave

Unfortunately I am no good at neither Vimscript and Go so not sure if that makes any sense.

**Comment by mschenk42** [comment]
I'll do some investigation on this.  I may tweak the algorithm so it doesn't add idle time for the last event.

**Comment by nicknikolov** [comment]
Thank you!
