### ISSUE TITLE
Undo gtm init

### ISSUE THREAD

**Issue by kchristidis** [git-time-metric/gtm#4]
If I no longer want to track a project with `gtm`, how do I undo all the changes that were incurred by the `gtm init` command?

**Comment by gradymke** [comment]
I'm pretty sure you can simply remove the .gtm directory and it will stop tracking.

**Comment by mschenk42** [comment]
I'd also remove the git post-commit hook.  You can do this by deleting the `.git/hooks/post-commit` file.  If you had an existing`post-commit` before initializing GTM, you can update the post-commit by removing `gtm commit --yes` line.

To make this easier we will add a GTM CLI command for uninitializing a repo.

**Comment by kchristidis** [comment]
Thanks for the quick response, this worked great.

Adding a CLI command would be neat.

@mschenk42: Do you want me to close this issue, or keep it open until the CLI command is added?

**Comment by mschenk42** [comment]
NP, let's keep it open to track the new feature

**Comment by mschenk42** [comment]
I've added a couple of CLI commands in the latest release.

`gtm uninit` to uninitialize gtm for a project
`gtm clean` to clear uncommitted time data

[Release v1.0-beta.7](https://github.com/git-time-metric/gtm/releases/tag/v1.0-beta.7)
