### ISSUE TITLE
Time tracked seems to get erased when rebasing

### ISSUE THREAD

**Issue by mbeasley** [git-time-metric/gtm#53]
I'm new to using GTM, so I apologize if the solution to this problem is obvious or if this just isn't in the capabilities of GTM.

If I use GTM to track time on a handful of local commits on master and then try to rebase with origin, replaying my local commits on top of origin (rather than merging upstream changes), all of the GTM data that is tracked along side those local commits disappears.

Is there a way to avoid this or to recover that data or implement this? I'm thinking some type of `post-rewrite` hook may help here, so I'll start looking at how I might use that, but if anyone working on this project has any insight here, I know I'd appreciate it.

**Comment by mschenk42** [comment]
Check to see if this is set to false, by default it is set to true, https://git-scm.com/docs/git-notes#git-notes-notesrewriteltcommandgt 

We also set https://git-scm.com/docs/git-notes#git-notes-notesrewriteRef  to `rewriteref = refs/notes/gtm-data` in the `.git/config`.

If you can please share your `.git/config` so I can take a look.

**Comment by mbeasley** [comment]
Sorry for the delay. Here's my [global git config](https://github.com/mbeasley/dotfiles/blob/master/.gitconfig) and here's the relevant section from my repo's git config:

```
[core]
  repositoryformatversion = 0
  filemode = true
  bare = false
  logallrefupdates = true
...
[notes]
  rewriteref = refs/notes/gtm-data
[alias]
  pushgtm = push origin refs/notes/gtm-data
  fetchgtm = fetch origin refs/notes/gtm-data:refs/notes/gtm-data
```

**Comment by mbeasley** [comment]
Just as an update, I've made a bare git repo to just try replicate this behavior explicitly and can reproduce it just fine.

**Comment by mschenk42** [comment]
In your global git config, I'm guessing this may be problematic:

[merge]
	# Include summaries of merged commits in newly created merge commit messages
	log = true

Could you temporarily remove your global git config and try creating a new repo and see what happens?

**Comment by mbeasley** [comment]
That was it. Thanks for working through that.
