### ISSUE TITLE
VS Code bug - property document

### ISSUE THREAD

**Issue by ajsb85** [git-time-metric/gtm#55]
Hi @nexus-uw

I can see this error message in the devtools:

`shell.ts:433 Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined at C:\<extensions-path>\s3ramsay.vscode-gtm-0.1.2\out\src\extension.js:49:88`

- VSCode Version: Code - Insiders 1.9.0-insider (39d761bf1f4ce7ea605539bdba41a8727b3c7ce0, 2017-01-18T07:10:04.990Z)
- OS Version: Windows_NT ia32 10.0.15007
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.1|
|jshint|dbaeumer|0.10.15|
|ghlink|dt|0.0.4|
|EditorConfig|EditorConfig|0.3.4|
|Theme-Zenburn|gerane|0.0.3|
|sass-lint|glen-84|0.0.3|
|vscode-commitizen|KnisterPeter|0.3.5|
|vscode-github|KnisterPeter|0.9.0|
|debugger-for-chrome|msjsdiag|2.4.2|
|vscode-docker|PeterJausovec|0.0.11|
|gitlink|qezhu|0.0.1|
|sass-indented|robinbentley|1.3.0|
|sharecode|RolandGreim|0.4.0|
|vscode-gtm|s3ramsay|0.1.2|

---

Steps to Reproduce:

1. Open the Extension list of the sidebar
2. Select any extension

**Comment by mschenk42** [comment]
I see that too.  The plugin seems to be working fine for me even with this error.  Is GTM tracking your time?  

Not sure why you are getting this error. I'm not the author of this plugin and my knowledge of typescript is minimal.   BTW, this is the main repo for the plugin, https://github.com/nexus-uw/vscode-gtm. 

Any guidance on how to fix this?

**Comment by mschenk42** [comment]
See issue here https://github.com/nexus-uw/vscode-gtm/issues/12
