### ISSUE TITLE
libssl.so.1.0.0 not found

### ISSUE THREAD

**Issue by nexeck** [git-time-metric/gtm#58]
```
gtm: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

Distro: Fedora 25
Installed OpenSSL:
/usr/lib64/libssl.so.1.0.2j
/usr/lib64/libssl.so.10

Installed Packages
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2j
Release     : 3.fc25

**Comment by mschenk42** [comment]
I'll try booting up a Fedora vm and take a look.

**Comment by mschenk42** [comment]
We actually do not need libssl.  The build automatically picks it up if it finds the library when building.  I've removed the libssl package before building, so it shouldn't be linked now.  

Please try out this new build and let me know if it works or not.  Thanks.

https://github.com/git-time-metric/gtm/releases/tag/v1.2.6-beta.1

**Comment by nexeck** [comment]
Thank you, this is working for me :)

Thanks for the quick fix :)

**Comment by mschenk42** [comment]
Excellent 👍
