### ISSUE TITLE
Used by projects?

### ISSUE THREAD

**Issue by kszucs** [git-time-metric/gtm#65]
Are there a list of projects using `gtm`?

I'd like to create a dataset for experiments/statistics on development time required by different programming languages.

**Comment by mschenk42** [comment]
There isn't a list of projects using gtm.  Since gtm is decentralized, it will be tough to gather that data via gtm.  I'd checkout https://wakatime.com/ to see if you can extract these metrics from their site.  They publish leaderboards and give statistics around languages and time spent.

**Comment by kszucs** [comment]
A couple of larger projects would be enough. 
I could search for `refs/notes/gtm-data` in github API endpoints like https://api.github.com/repos/git-time-metric/gtm/git/refs, but checking all the repos seems exhausting.

BTW is there an easy way to export gtm-data in a machine readable way (json, csv etc.)?

**Comment by mschenk42** [comment]
I don't think you can get access to the commit level statisics for Waka time for repos other than your own.

Currently you can't export as json or csv but I may add it in the future.

**Comment by kszucs** [comment]
FYI there is a conversation about publishing a dataset wakatime/wakatime#77
