### ISSUE TITLE
How I can organize JIRA smart commits?

### ISSUE THREAD

**Issue by max-mykhailenko** [git-time-metric/gtm#72]
Jira can collect spent time from commit messages. Commit message format should be `issue-123 #time 1h 10m`. Issue name I can get from current branch name, but how I can get time spent from last commit?

**Comment by mschenk42** [comment]
In your pre-commit hook you can use `gtm status --total-only`.  It doesn't match the time format for what Jira expects.   I've been thinking about adding this option for a while.  I'll create an issue for this and see what I can do to get it done.

**Comment by mschenk42** [comment]
Information on Jira Smart Commits - https://confluence.atlassian.com/bitbucket/processing-jira-software-issues-with-smart-commit-messages-298979931.html#id-_smart_commits_commands1-time

**Comment by mschenk42** [comment]
I've added the ability to output the time spent in a format that is compatible with Jira.

`gtm status --total-only --long-duration`
14 minutes

**Comment by max-mykhailenko** [comment]
Excellent! Thank you.
