### ISSUE TITLE
Release 1.3.2 libssl.so.1.0.0 not found

### ISSUE THREAD

**Issue by guenhter** [git-time-metric/gtm#78]
When I extract the gtm-tar 1.3.2-linux, and execute the `./gtm`, I get:

```
./gtm: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

Note: This doesn't happen with older releases like `1.2.11-linux`

**Comment by mschenk42** [comment]
Sorry about that, try this release, https://github.com/git-time-metric/gtm/releases/tag/v1.3.3-beta

**Comment by guenhter** [comment]
Nope,  still same problem.

**Comment by mschenk42** [comment]
Looks like I may have fixed this in the past and inadvertently removed it. https://github.com/git-time-metric/gtm/commit/52da5ffacd1923488c42a266fd70c425db3e7286
I'll update the build and we can see if that works for you.

**Comment by guenhter** [comment]
If the library is needed by the plugin, I guess it's just a prerequisite for the plugin. In that case, it would be helpful to provide an installation instruction.

**Comment by guenhter** [comment]
This fixed the problem. Thx
