### ISSUE TITLE
Bug: `gtm status` empty result. 

### ISSUE THREAD

**Issue by hackintoshrao** [git-time-metric/gtm#8]
Thanks for the worderful tool. 
Here is the issue I'm facing, 

- I've used pathogen to install the `gtm vim` plugin, 
- And have initialized gtm on the my repo. 
- But gtm status is showing empty result after code edits/modifications.

**Comment by mschenk42** [comment]
Can you check if you have a `.gtm` directory in the root of your git repo and then check if there are .event files being created as you open, save and navigate around within Vim.  You should have new event files created at a minimum every 30 seconds when you are active in Vim.

Also try running `gtm status`.

Keep in mind there will be nothing to report on until you commit, otherwise you can look at work-in-progress with `gtm status`.

**Comment by hackintoshrao** [comment]
.gtm exists, but its empty and I don't see `.event` files being generated. 

`gtm status` too shows empty result on code modifications.

**Comment by gradymke** [comment]
What editor and plugin are you using to capture the "record" events? It very well could be that there is a problem with the plugin that we need to dive into.

**Comment by mschenk42** [comment]
Can you try `echom GTMStatusline()` from within Vim?  This shouldn't return an error if the plugin is installed.  

I'm guessing the plugin is not being loaded.  Can you also share the snippet from your `.vimrc` where you load the gtm plugin?

**Comment by hackintoshrao** [comment]
@mschenk42 @gradymke , I followed the instructions [here](https://github.com/git-time-metric/gtm-vim-plugin) . 
- git clone https://github.com/git-time-metric/gtm ~/.vim/bundle/gtm
- gtm init in my repo 
- Added the following configuration to vimrc ( I use Airline) . 

  `let g:gtm_plugin_status_enabled = 1 `

```
function! AirlineInit()
  if exists('*GTMStatusline')
    call airline#parts#define_function('gtmstatus', 'GTMStatusline')
    let g:airline_section_b = airline#section#create([g:airline_section_b, ' ', '[', 'gtmstatus', ']'])
  endif
endfunction
autocmd User AirlineAfterInit call AirlineInit()
```

**Comment by mschenk42** [comment]
I haven't tested using Pathogen to load gtm but I will sometime this evening to make sure the instructions work.  The instructions assume Pathogen is already installed in your .vimrc and is working.  Currently I'm using Plug to install gtm and not Pathogen.

Are you using Pathogen to install other plugins and is it working as expected?

**Comment by hackintoshrao** [comment]
@mschenk42 : Yes, I've been using pathogen from an year now, I've customized my vim editor using tens of packages installed via `pathogen`(including Airline).

**Comment by mschenk42** [comment]
I tested with Pathogen and worked for me.  Would you be able to share your .vimrc and tell me what version of Vim you are running?  I'm currently running the latest release of neovim.

The only difference I have compared to the instructions is the name of gtm plugin directory.  Here's what mine is.
```
❯ ls ~/.vim/bundle |grep gtm-vim-plugin
gtm-vim-plugin
```

**Comment by mschenk42** [comment]
Can you also do a `gtm --version` from the command line and let me know the results? Thanks.

**Comment by mschenk42** [comment]
BTW, here's my [dotfiles](https://github.com/mschenk42/dotfiles) using "Plug".

**Comment by hackintoshrao** [comment]
- Vim version `VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2015 16:22:14)`
- gtm version `v1.0-beta.8` 
- Here is my vimrc
```
execute pathogen#infect()
syntax on       
filetype plugin indent on

let mapleader=","
        
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <Leader>s <Plug>(go-implements)au FileType go nmap <Leader>s <Plug>(go-implements)
                
set laststatus=2
        
let g:gtm_plugin_status_enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1

        
function! AirlineInit()
          if exists('*GTMStatusline')
                call airline#parts#define_function('gtmstatus', 'GTMStatusline')
                let g:airline_section_b = airline#section#create([g:airline_section_b, ' ', '[', 'gtmstatus', ']'])
          endif
endfunction     
autocmd User AirlineAfterInit call AirlineInit()
        
        
set runtimepath^=~/.vim/bundle/ctrlp.vim
                

```

**Comment by mschenk42** [comment]
I tested Vim 7.3 with your same configuration.  I have a lot of the same plugins so your .vimrc just worked fine for me.  Here's the Vim version I tested.

```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Apr  5 2016 14:53:37)
```

What OS are you running?

**Comment by mschenk42** [comment]
Can you also tell me what you get when you run `echom GTMStatusline()` within Vim?

**Comment by mschenk42** [comment]
I'm leaning towards this might be a conflict with one of your other plugins.  I believe you only sent a portion of your .vimrc.  Is that correct?  

If so, one way to determine this is just to load the gtm plugin and maybe airline to see if it works.  If it does, then you can troubleshoot by adding other plugins back in one at a time.

**Comment by hackintoshrao** [comment]
- I'm running OSX El Capitan 10.11.3
- I see  `E117: Unknown function: GTMStatusline`
`E15: Invalid expression: GTMStatusline()` on running `echom GTMStatusline()` 
- What I posted was my entire `.vimrc`, its minimal. 
- Let me just load gtm and see if it works.

**Comment by hackintoshrao** [comment]
No Luck, will move to Plug.

**Comment by mschenk42** [comment]
Sorry to hear that, let me know if you have any questions about Plug and gtm.

**Comment by mschenk42** [comment]
@hackintoshrao this might be why you were having issues with installing via Pathogen,
see this issue https://github.com/git-time-metric/gtm-vim-plugin/issues/2

**Comment by hackintoshrao** [comment]
@mschenk42 : Let me try this out now. Couldnt try out with Plug.

**Comment by hackintoshrao** [comment]
@mschenk42 : Its working with vim-pathogen now, thanks!

**Comment by Graystripe17** [comment]
@hackintoshrao Hi, I'm using plug and have this same problem. Vim 8.0 on High Sierra. I have enabled gtm terminal as well and that works fine. gtm status is not blank anymore, but was before I added terminal plugin. gtm report lists my latest commit

```
set number

syntax on

colorscheme monokai

set mouse=a		" Mouse can navigate

set hlsearch		" Highlight search

set incsearch		" Highlight matches

"Turn off search highlight with ,<space>
nnoremap <leader>h :nohlsearch<CR>

" Note the change to 3 spaces for the stupid Java class
filetype plugin indent on

autocmd Filetype java setlocal tabstop=3 softtabstop=3 shiftwidth=3 expandtab " For Java

set tabstop=4		" Visual spaces per tab
set softtabstop=4	" Number of spaces in tab when editing
set expandtab		" Tabs are spaces

set showmatch		" Highlight matching [{()}]

set foldenable		" Enable folding

" Status line highlighting Monokai
" 272822 Sundried Clay
" F92672 Pink Orchard
" 66D9EF Bounded Rationality
" A6E22E Henn1nk
" FD971F Pumpkin Spice
hi StatusLine                  ctermfg=3          ctermbg=272822     cterm=NONE
hi StatusLineNC                ctermfg=272822     ctermbg=66D9EF     cterm=NONE

" Change cursor color
set cursorline
hi Cursor ctermbg=172
hi CursorLine ctermbg=18
hi CursorIM ctermbg=100
" Add jk to esc
:imap jk <Esc>
" Enable copying out
:vnoremap <C-c> :w !pbcopy<CR><CR>

call plug#begin('~/.vim/plugged')

Plug 'crusoexia/vim-monokai'
Plug 'pangloss/vim-javascript'
Plug 'git-time-metric/gtm-vim-plugin'

call plug#end()

```

**Comment by mschenk42** [comment]
Your config looks right for installing gtm using Plug.  Are you still having issues?  If so, please give examples of what issues you are seeing.
