### ISSUE TITLE
installer for windows not working

### ISSUE THREAD

**Issue by jmdmao** [git-time-metric/gtm#80]
I downloaded the file available on the download link for windows, unzipped via winrar, and tried to run.

When run, gtm.exe only flashes and then closes.

did I do something wrong?

**Comment by mschenk42** [comment]
I think you may have download the latest which doesn't have a Windows installer included.  I'm currently working on a Linux build issue and haven't included a Windows installer yet.  Try this release https://github.com/git-time-metric/gtm/releases/tag/v1.3.2 and run the installer `gtm-v1.3.2-windows-installer.exe`.

**Comment by mschenk42** [comment]
Just cut a new release, https://github.com/git-time-metric/gtm/releases/tag/v1.3.3

**Comment by jmdmao** [comment]
Thanks! Works like a charm!

Before closing, a question:

In Gitlab, there is the possibility of adding the estimated time and the time spent. Does the time information that the plugin provides integrate with Gitlab?

**Comment by jmdmao** [comment]
Unfortunately, I don't use GIRA. But thank's anyway.

**Comment by mschenk42** [comment]
You can do a pre-commit git hook and use `gtm status --total-only` to get the time spent and automatically add it to the git commit message.

**Comment by jmdmao** [comment]
Ah ok. Thanks! 😄
