### ISSUE TITLE
Accessing the tracked data outside of gtm

### ISSUE THREAD

**Issue by gazsp** [git-time-metric/gtm#88]
I understand that gtm uses git notes to store the time tracking metrics, but how can I access the raw data myself, without using gtm? The use case would be taking the gtm data and feeding it into another program.

Is there some documentation on how to access the raw data and / or what the data format is?

Thanks in advance.

(P.S. I saw a comment somewhere on another issue about CSV / JSON export - that would be really useful!)

**Comment by mschenk42** [comment]
Here's one way to get the raw data from the command line.  It's a custom format.

 `git notes --ref gtm-data show HEAD`

**Comment by gazsp** [comment]
Awesome. Any info on the format? ;-)

**Comment by gazsp** [comment]
Thanks for the info!
